# Generated by Django 3.0.6 on 2020-05-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
